name: Publish Docker

on:
  push:
    branches:
      - 'master'
      - 'react-rewrite'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sibbl/wohnung-scraper
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        registry: docker.pkg.github.com
